apiVersion: v1
kind: Service
metadata:
  name: mediator
spec:
  type: LoadBalancer
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
      nodePort: 30163
      protocol: TCP
  selector:
    app: mediator
