apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mediator
  name: mediator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mediator
  strategy: { }
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: mediator
    spec:
      containers:
        - image: mpinchuk/mediator:latest
          imagePullPolicy: ""
          name: mediator
          ports:
            - containerPort: 8081
          resources: { }
      restartPolicy: Always
      serviceAccountName: ""
status: { }
